
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[221] =
    {   0,
        0,    0,   71,   69,   68,   67,   67,   69,   69,   65,
       47,   31,   69,   52,   32,   48,   55,   34,   46,   36,
       35,   61,   61,   33,   60,   44,    4,   38,   63,   63,
       63,   63,   63,   63,   63,   29,   66,   14,   59,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   54,   49,   67,   67,   51,    0,   64,    0,
       65,    7,    1,    0,   64,    0,   56,    8,   10,    6,
       57,   61,   41,    2,   61,   61,    0,    0,    0,    0,
        0,    0,   61,    0,   42,   45,   43,   37,   39,   58,
       63,    0,    0,   63,   63,   63,   63,   13,   63,   63,

       63,   63,   63,   63,   63,   63,   63,   63,   63,   24,
       40,   63,   53,   63,   63,    9,   67,   67,   67,   64,
        0,    0,   11,   61,    0,    3,    0,   61,    0,    0,
       61,   61,    0,   61,    0,   61,    5,   12,   63,   63,
       63,   63,   63,   63,   30,   63,   63,   63,   22,   63,
       63,   63,   63,   21,   63,   50,   63,   63,    0,    0,
        0,    0,    0,    0,   61,    0,   63,   25,   27,   63,
       63,   63,   63,   63,   63,   63,   18,   19,   63,   63,
       63,   63,    0,    0,   20,   63,   63,   63,   15,   16,
       63,   63,   63,   63,   63,   28,   64,   63,   63,   63,

       63,   63,   63,   23,   26,   63,   63,   63,   63,   63,
       63,   62,   17,   63,   63,   63,   63,   61,   63,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,    1,    1,   28,   29,   28,   28,   30,   31,
       32,   32,   32,   33,   32,   32,   32,   34,   35,   32,
       32,   36,   32,   37,   38,   32,   32,   39,   32,   32,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   32,   61,   62,   63,   64,   32,   65,   66,
       32,   32,    1,   67,    1,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1
    } ;

static const flex_int16_t yy_base[229] =
    {   0,
        0,    0,  450,  451,  451,   67,   73,  423,   66,    0,
      422,  421,   63,  451,  451,   65,  420,  451,   55,   64,
       61,   91,   73,  451,  451,   71,  419,   62,    0,   95,
      108,  385,   96,  382,  109,  451,  451,  451,  416,  397,
      382,  118,   73,   85,  383,  135,  382,   89,  378,  375,
      149,  383,  408,  451,  158,  170,  451,  110,  427,    0,
        0,  451,  451,  123,  422,    0,  405,  451,  451,  451,
      451,  162,  404,  451,  167,  183,  198,  189,  215,  202,
      385,  219,  231,  235,  402,  451,  451,  451,  451,  401,
        0,  117,  126,  142,  370,  367,  360,  451,  205,  375,

      220,  377,  363,  370,  368,   47,  359,  356,  357,    0,
        0,  352,    0,  351,  360,  451,  263,  269,  275,  451,
      160,  166,  451,  264,  268,  451,  276,  205,  224,  280,
      284,  272,  290,  368,  367,  300,  451,  451,  348,  360,
      359,  349,  361,  360,    0,  359,  341,  339,    0,  348,
      350,  350,  353,    0,  351,    0,  332,  339,  169,  388,
      160,  204,  383,  187,  304,  312,  343,    0,    0,  338,
      337,  332,  333,  322,  326,  300,    0,    0,  294,  306,
      286,  297,  339,  333,    0,  279,  283,  291,    0,    0,
      281,  278,  279,  280,  277,    0,  451,  285,  283,  274,

      251,  269,  248,    0,    0,  263,  230,  224,  215,  198,
      155,    0,    0,  122,  122,  227,  100,    0,   82,  451,
      349,  355,  361,  363,  369,   94,  375,  381
    } ;

static const flex_int16_t yy_def[229] =
    {   0,
      220,    1,  220,  220,  220,  220,  220,  220,  221,  222,
      220,  220,  223,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  224,  224,
      224,  224,  224,  224,  224,  220,  220,  220,  220,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  220,  220,  220,  225,  220,  221,  220,  221,
      222,  220,  220,  223,  220,  223,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      226,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      224,  221,  223,  224,  224,  224,  224,  220,  224,  224,

      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  220,  225,  225,  225,  220,
      227,  228,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  226,  226,  220,  220,  220,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  227,  220,
      227,  228,  220,  228,  220,  220,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  220,  220,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  220,  224,  224,  224,

      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,    0,
      220,  220,  220,  220,  220,  220,  220,  220
    } ;

static const flex_int16_t yy_nxt[520] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   24,   25,   26,   27,   28,   29,   30,   29,
       31,   29,   29,   32,   29,   33,   34,   35,   29,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   29,   48,   29,   29,   29,   29,   49,   50,   29,
       51,   29,   29,   35,   52,   29,   53,   54,   55,   55,
       55,   59,   65,   56,   55,   55,   55,   67,   73,   56,
       70,   71,   72,   72,   72,   72,   74,   89,   90,   75,
       68,   83,   83,   83,   83,   85,   86,   87,  134,  151,

       92,   92,   79,   66,   93,   93,   60,   75,  152,   76,
       77,   77,   77,   92,   92,  120,   84,   93,   93,   78,
       79,   79,   59,   92,   94,   80,   94,   93,  102,   81,
       94,  103,  120,  104,   82,   65,   78,  105,  110,   79,
       92,   94,  216,   94,   93,   94,  111,   92,  219,   80,
       60,   93,   95,   94,   92,   94,   81,   60,   93,   55,
       55,   55,  220,   66,   56,  160,   66,  217,   94,  159,
       94,  118,   55,  118,  160,  163,  119,   94,  101,   94,
      124,  124,  124,  124,  216,   72,   72,   72,   72,  220,
      107,   79,  162,  108,   94,   94,   79,  114,   94,   75,

      161,   76,   77,   77,   77,  125,  164,  128,  128,  161,
       79,  215,   79,  163,   75,   79,   77,   77,   77,   77,
      132,  132,  132,  128,  128,   92,   82,   79,  130,   93,
      130,   79,  129,  131,  131,  131,  131,  136,   77,   77,
       77,  127,  128,  128,  164,  133,   79,   75,  129,   83,
       83,   83,   83,   83,   83,   83,   83,  142,  214,  218,
       79,  143,  144,  213,  118,   55,  118,  212,  146,  119,
      118,   55,  118,  212,   84,  119,  118,   55,  118,   79,
      218,  119,  124,  124,  124,  124,  124,  124,  124,  124,
      132,  132,  132,   79,   77,   77,   77,   77,  131,  131,

      131,  131,  165,  165,  165,  165,  212,  125,  132,  132,
      132,  211,   79,  210,  209,  133,   75,  208,  136,   77,
       77,   77,  165,  165,  165,  165,  207,  166,  206,   79,
      165,  165,  165,  165,  205,  204,  203,  202,  201,  200,
      199,  198,  197,   82,  197,  196,  195,  166,   79,   58,
      194,   58,   58,   58,   58,   61,  193,   61,   61,   61,
       61,   64,  192,   64,   64,   64,   64,   91,   91,  117,
      117,  117,  117,  117,  117,  159,  159,  159,  191,  159,
      159,  162,  162,  190,  162,  162,  162,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,

      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      220,  135,  158,  157,  156,  155,  154,  153,  150,  149,
      148,  147,  145,  141,  140,  139,  138,  137,  135,  126,
      123,  122,  121,  116,  115,  113,  112,  109,  106,  100,
       99,   98,   97,   96,   88,   69,   63,   62,   57,  220,
        3,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,

      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220
    } ;

static const flex_int16_t yy_chk[520] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    6,    6,
        6,    9,   13,    6,    7,    7,    7,   16,   21,    7,
       19,   19,   20,   20,   20,   20,   21,   28,   28,   23,
       16,   23,   23,   23,   23,   26,   26,   26,  226,  106,

       30,   33,   23,   13,   30,   33,    9,   22,  106,   22,
       22,   22,   22,   31,   35,   58,   23,   31,   35,   22,
       22,   23,   92,   42,   33,   22,   33,   42,   43,   22,
       30,   43,   64,   44,   22,   93,   22,   44,   48,   22,
       46,   33,  219,   31,   46,   33,   48,   94,  217,   22,
       58,   94,   31,   42,   51,   30,   22,   92,   51,   55,
       55,   55,  161,   64,   55,  121,   93,  215,   31,  161,
       46,   56,   56,   56,  159,  122,   56,   51,   42,   51,
       72,   72,   72,   72,  214,   75,   75,   75,   75,  164,
       46,   72,  164,   46,   51,   46,   75,   51,   51,   76,

      121,   76,   76,   76,   76,   72,  122,   78,   78,  159,
       72,  211,   76,  162,   77,   75,   77,   77,   77,   77,
       80,   80,   80,  128,  128,  101,   76,   77,   79,  101,
       79,   76,   78,   79,   79,   79,   79,   82,   82,   82,
       82,   77,  129,  129,  162,   80,   77,   83,  128,   83,
       83,   83,   83,   84,   84,   84,   84,   99,  210,  216,
       83,   99,   99,  209,  117,  117,  117,  208,  101,  117,
      118,  118,  118,  207,   83,  118,  119,  119,  119,   83,
      216,  119,  124,  124,  124,  124,  125,  125,  125,  125,
      132,  132,  132,  124,  127,  127,  127,  127,  130,  130,

      130,  130,  131,  131,  131,  131,  206,  124,  133,  133,
      133,  203,  124,  202,  201,  132,  136,  200,  136,  136,
      136,  136,  165,  165,  165,  165,  199,  131,  198,  136,
      166,  166,  166,  166,  195,  194,  193,  192,  191,  188,
      187,  186,  184,  136,  183,  182,  181,  165,  136,  221,
      180,  221,  221,  221,  221,  222,  179,  222,  222,  222,
      222,  223,  176,  223,  223,  223,  223,  224,  224,  225,
      225,  225,  225,  225,  225,  227,  227,  227,  175,  227,
      227,  228,  228,  174,  228,  228,  228,  173,  172,  171,
      170,  167,  163,  160,  158,  157,  155,  153,  152,  151,

      150,  148,  147,  146,  144,  143,  142,  141,  140,  139,
      135,  134,  115,  114,  112,  109,  108,  107,  105,  104,
      103,  102,  100,   97,   96,   95,   90,   85,   81,   73,
       67,   65,   59,   53,   52,   50,   49,   47,   45,   41,
       40,   39,   34,   32,   27,   17,   12,   11,    8,    3,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,

      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[71] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
#include "parser.tab.h"
#include "includes.hpp"
extern stack<int> indent_stack;
extern int global_indent;
extern int generated_EOF;
extern int ready_EOF;
extern int signal_EOF;
extern int entered_newline;
extern string last_token;
extern string last_token_value;
extern stack<char> brackets;
extern int terminated;

#line 671 "lex.yy.c"
#line 672 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 62 "lex.l"

#line 64 "lex.l"
 {
    if (global_indent > 0){
        global_indent--;
        last_token = "INDENT";
        return INDENT;
    }else if(global_indent < 0){
        global_indent++;
        last_token = "DEDENT";
        return DEDENT;
    }
 }
#line 903 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 221 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 451 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "lex.l"
{last_token="&=";yylval.node = makeNode(yytext,OPERATOR_TYPE);return ASSIGN_AND;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 76 "lex.l"
{last_token="/=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_DIVIDE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "lex.l"
{last_token="//=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_DOUBLESLASH;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "lex.l"
{last_token="=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_EQUAL;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "lex.l"
{last_token="<<=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_LEFTSHIFT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 80 "lex.l"
{last_token="-=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_MINUS;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "lex.l"
{last_token="%=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_MOD;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "lex.l"
{last_token="*=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_MULTIPLY;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 83 "lex.l"
{last_token="|=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_OR;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 84 "lex.l"
{last_token="+=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_PLUS;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 85 "lex.l"
{last_token="**=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_POWER;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "lex.l"
{last_token=">>=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_RIGHTSHIFT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 87 "lex.l"
{last_token="^=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return ASSIGN_XOR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 88 "lex.l"
{last_token="]";if (brackets.size() > 0 && brackets.top() == '['){brackets.pop();};yylval.node = makeNode(yytext,OPERATOR_TYPE); return CLOSE_SQUARE_BRACKET;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 89 "lex.l"
{last_token="break";yylval.node = makeNode(yytext,KEYWORD_TYPE); return KEY_BREAK;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 90 "lex.l"
{last_token="class";yylval.node = makeNode(yytext,KEYWORD_TYPE); return KEY_CLASS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "lex.l"
{last_token="continue";yylval.node = makeNode(yytext,KEYWORD_TYPE); return KEY_CONTINUE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "lex.l"
{last_token="elif";yylval.node = makeNode(yytext,ELIF_STATEMENT_TYPE); return KEY_ELIF;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 93 "lex.l"
{last_token="else";yylval.node = makeNode(yytext,ELSE_STATEMENT_TYPE); return KEY_ELSE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 94 "lex.l"
{last_token="False";yylval.node = makeNode(yytext,BOOLEAN_TYPE); return KEY_FALSE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 95 "lex.l"
{last_token="for";yylval.node = makeNode(yytext,FOR_STATEMENT_TYPE); return KEY_FOR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 96 "lex.l"
{last_token="def";yylval.node = makeNode(yytext,KEYWORD_TYPE); return KEY_FUNCTION_DEF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 97 "lex.l"
{last_token="global";yylval.node = makeNode(yytext,KEYWORD_TYPE); return KEY_GLOBAL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 98 "lex.l"
{last_token="if";yylval.node = makeNode(yytext,IF_STATEMENT_TYPE); return KEY_IF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 99 "lex.l"
{last_token="None";yylval.node = makeNode(yytext,NAME_TYPE); return KEY_NONE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 100 "lex.l"
{last_token="return";yylval.node = makeNode(yytext,KEYWORD_TYPE); return KEY_RETURN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 101 "lex.l"
{last_token="True";yylval.node = makeNode(yytext,BOOLEAN_TYPE); return KEY_TRUE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 102 "lex.l"
{last_token="while";yylval.node = makeNode(yytext,WHILE_STATEMENT_TYPE); return KEY_WHILE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 103 "lex.l"
{last_token="[";brackets.push('[');yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPEN_SQUARE_BRACKET;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 104 "lex.l"
{last_token="and";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_AND;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 105 "lex.l"
{last_token="&";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_AND_BITWISE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 106 "lex.l"
{last_token=")";if (brackets.size() > 0 && brackets.top() == '('){brackets.pop();};yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_CLOSE_BRACKET;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 107 "lex.l"
{last_token=":";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_COLON;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "lex.l"
{last_token=",";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_COMMA;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 109 "lex.l"
{last_token="/";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_DIVIDE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 110 "lex.l"
{last_token=".";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_DOT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 111 "lex.l"
{last_token="==";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_EQUAL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 112 "lex.l"
{last_token=">";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_GREATER_THAN;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 113 "lex.l"
{last_token=">=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_GREATER_THAN_EQUAL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 114 "lex.l"
{last_token="in";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_IN;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 115 "lex.l"
{last_token="//";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_INT_DIV;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 116 "lex.l"
{last_token="<<";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_LEFT_SHIFT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 117 "lex.l"
{last_token="<>";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_LESS_GREATER;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 118 "lex.l"
{last_token="<";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_LESS_THAN;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 119 "lex.l"
{last_token="<=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_LESS_THAN_EQUAL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 120 "lex.l"
{last_token="-";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_MINUS;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 121 "lex.l"
{last_token="%";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_MOD;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 122 "lex.l"
{last_token="*";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_MULTIPLY;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 123 "lex.l"
{last_token="~";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_NEGATIVE;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 124 "lex.l"
{last_token="not";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_NOT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 125 "lex.l"
{last_token="!=";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_NOT_EQUAL;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 126 "lex.l"
{last_token="("; brackets.push('(');yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_OPEN_BRACKET;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 127 "lex.l"
{last_token="or";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_OR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 128 "lex.l"
{last_token="|";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_OR_BITWISE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 129 "lex.l"
{last_token="+";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_PLUS;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 130 "lex.l"
{last_token="**";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_POWER;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 131 "lex.l"
{last_token="->";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_REFERENCE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "lex.l"
{last_token=">>";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_RIGHT_SHIFT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 133 "lex.l"
{last_token="^";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_XOR_BITWISE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 134 "lex.l"
{last_token=";";yylval.node = makeNode(yytext,OPERATOR_TYPE); return OPER_SEMICOLON;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 135 "lex.l"
{last_token="NUMBER";last_token_value=yytext;yylval.node = makeNode(yytext,NUMBER_TYPE); return NUMBER;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 136 "lex.l"
{last_token="NAME";last_token_value=yytext;yylval.node = makeNode(yytext,NAME_TYPE); return NAME;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 137 "lex.l"
{last_token="NAME";last_token_value=yytext;yylval.node = makeNode(yytext,NAME_TYPE); return NAME;}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 138 "lex.l"
{last_token="STRING";last_token_value=yytext;yylval.node = makeNode(yytext,STRING_TYPE); return STRING;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 139 "lex.l"
{}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 140 "lex.l"
{last_token = "\\";}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 141 "lex.l"
{
    if (last_token != "\\" && brackets.size() == 0){
        string spaces = yytext;
        int len = 0;
        for (auto c: spaces){
            if (c == ' ' || c == '\t') len++;
            if (c == '\n') len = 0;
        }
        int top = indent_stack.top();
        if(len > top) {
            global_indent++;
            indent_stack.push(len);
        }
        else{
            while (len < top){
                indent_stack.pop();
                top = indent_stack.top();
                global_indent--;
            }
        }
        last_token = "NEWLINE";
        yylval.node = makeNode("\n",MISC_TYPE);return NEWLINE;
    }
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 165 "lex.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 167 "lex.l"
{
    if (!ready_EOF){
        if (!entered_newline && last_token != "DEDENT"){
            entered_newline = 1;
            return NEWLINE;
        }
        if (indent_stack.size() > 1){
            indent_stack.pop();
            last_token = "DEDENT";
            return DEDENT;
        }else if (indent_stack.size() == 1){
            ready_EOF = 1;
            last_token = "NEWLINE";
            return NEWLINE;
        }
    }
    if (ready_EOF){
        if (generated_EOF){
            return 0;
        }
        generated_EOF = 1;
        yylval.node = makeNode("ENDMARKER",MISC_TYPE); return ENDMARKER;
    }
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 192 "lex.l"
{
    terminated = 1;
    cerr << "Error: Unrecognized token " << yytext << " at line " << yylineno << endl;
    yyterminate();
    return 0;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 199 "lex.l"
ECHO;
	YY_BREAK
#line 1377 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 221 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 221 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 220);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 199 "lex.l"


int yywrap() {
    return 1;
}


